package iut.dam.sae_dam.errors;

public enum Errors {
    EMPTY,
    EMPTY_FIELD,
    INVALID_MAIL_FORMAT,
    INVALID_PASSWORD_FORMAT,
    INVALID_PASSWORD_CONFIRMATION,
    ACCOUNT_ALREADY_EXISTS,
    INVALID_MAIL_PASSWORD,
    INVALID_NEW_PASSWORD,
    NO_ACCOUNT_FOUND,
    INVALID_QUESTION_ANSWER,
    UNKNOWN_MEDICINE,
    UNKNOWN_PHARMACY,
    UNKNOWN_CITY,
    INVALID_OLD_PASSWORD,
    SAME_PASSWORD,
}
